services:
  whisper-app:
    build: .
    ports:
      - "9854:9854"
    volumes:
      - ./keys.txt:/app/keys.txt
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    group_add:
      - video
